config/routes.rb
DrugFinderDb::Application.routes.draw do
  resources :statistics
  resources :users
  resources :suppliers  do
     get :find, on: :collection
  end
  resources :holders do
    get :find, on: :collection
  end
  resources :producers  do
    get :find, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :drugs do
    get :search, on: :collection
    get :wide_search, on: :collection
    get :body_clicked_search, on: :collection
    get :show, on: :collection
  end

  root :to => 'home#index'

  match '/drugs/:id'           =>  'drugs#show',                      via: :get
  match 'holders/:name/find'   =>  'holders#find',                    :as => 'holders_find'
  match 'holders/:id/drugs'    =>  'holders#show_all',                :as => 'holders_show_all_drugs'
  match 'suppliers/:name/find' =>  'suppliers#find',                  :as => 'suppliers_find'
  match 'suppliers/:id/drugs'  =>  'suppliers#show_all',              :as => 'suppliers_show_all_drugs'
  match 'producers/:name/find' =>  'producers#find',                  :as => 'producers_find'
  match 'producers/:id/drugs'  =>  'producers#show_all',              :as => 'producers_show_all_drugs'
  match '/signin',             to: 'sessions#new'
  match '/signout',            to: 'sessions#destroy',                via: :delete
  match '/about',              to: 'static_pages#about'
  match '/contact',            to: 'static_pages#contact'
  match '/find_specific',      to: 'home#findSpecific'
  match '/stats',              to: 'statistics#stats'
  match '/find_producers',     to: 'producers#find_producers'
  match '/find_suppliers',     to: 'suppliers#find_suppliers'
  match '/find_holders',       to: 'holders#find_holders'
  match '/human_body',         to: 'static_pages#body'
  match '/clicks/:id',         to: 'clicks#incr_clicks',              via: :post

end

app/models/producer.rb
# == Schema Information
#
# Table name: producers
#
#  id         :integer          not null, primary key
#  name       :string(400)
#  name_clean :string(400)
#

class Producer < ActiveRecord::Base
  attr_accessible :id, :name
  has_many :drugs

  def self.find_producers_like_name name
    Producer.where(["name_clean ILIKE ?", "#{name}%"])
  end

  def self.find_by_producer_id id
    Drug.where("producer_id = ?", "#{id}")
  end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

  def find
    @producer = Producer.find_producers_like_name params[:producer_name]
  end

  def show_all
    drug_ = Producer.find_by_producer_id params[:id]
    @drug = drug_.paginate(page: params[:page])
  end
  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @producers }
    end
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
    @producer = Producer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producer }
    end
  end

  # GET /producers/new
  # GET /producers/new.json
  def new
    @producer = Producer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producer }
    end
  end

  # GET /producers/1/edit
  def edit
    @producer = Producer.find(params[:id])
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(params[:producer])

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render json: @producer, status: :created, location: @producer }
      else
        format.html { render action: "new" }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /producers/1
  # PUT /producers/1.json
  def update
    @producer = Producer.find(params[:id])

    respond_to do |format|
      if @producer.update_attributes(params[:producer])
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer = Producer.find(params[:id])
    @producer.destroy

    respond_to do |format|
      format.html { redirect_to producers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_for(@producer) do |f| %>
  <% if @producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% @producer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id, :placeholder => Producer.last.id + 1 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producers/_organization.html.erb
<div class="pocetVysledkov">
  <b>Počet výsledkov:  <%= @producer.count %>&nbsp; &nbsp; &nbsp; <%= link_to 'Naspäť', :back %></b>
</div>

<% @producer.each do |producer| %>

    <div class="foundResults">

      <div class="cast name">
        <%= producer.name_clean %>
      </div>

      <% if signed_in? && current_user.admin? %>
          <%= link_to 'Edit', edit_producer_path(producer) %> |
          <%= link_to 'Destroy', '#' %>
          <br>
      <% end %>
      <div class="cast store button" id="storeButton">
        <%= link_to 'Zobraziť všetky lieky', producers_show_all_drugs_path(producer.id) %>
      </div>

    </div>
<% end %>

<br>

<%= link_to 'Back', :back %>

app/views/producers/edit.html.erb
<h1>Editing producer</h1>

<%= render 'form' %>

<%= link_to 'Show', @producer %> |
<%= link_to 'Back', producers_path %>

app/views/producers/find.erb
<p id="notice"><%= notice %></p>

<%= render 'producers/organization' %>

app/views/producers/find_producers.erb
<% provide(:title, 'Rozšírené vyhľadávanie') %>

<div class="center hero-unit">
  <h1>Nájdi výrobcu</h1>

  <%= form_tag find_producers_path, method: :get do %>

      <p>
        <%= text_field_tag(:producer_name, '', :placeholder => 'Zadajte názov organizácie     Príklad: zentiva') %>
        <%= submit_tag 'Hľadaj', class: "btn btn-large btn-primary" %>
      </p>

  <% end %>
</div>

app/views/producers/index.html.erb
<h1>Listing producers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @producers.each do |producer| %>
  <tr>
    <td><%= producer.id %></td>
    <td><%= producer.name %></td>
    <td><%= link_to 'Show', producer %></td>
    <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
    <td><%= link_to 'Destroy', producer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producer', new_producer_path %>

app/views/producers/new.html.erb
<h1>Nový výrobca</h1>

<%= render 'form' %>

<%= link_to 'Back', producers_path %>

app/views/producers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @producer.id %>
</p>

<p>
  <b>Name:</b>
  <%= @producer.name %>
</p>


<%= link_to 'Edit', edit_producer_path(@producer) %> |
<%= link_to 'Back', producers_path %>

app/views/producers/show_all.erb
<p id="notice"><%= notice %></p>

<%= render :template => 'drugs/_drug' %>