config/routes.rb
DrugFinderDb::Application.routes.draw do
  resources :statistics
  resources :users
  resources :suppliers  do
     get :find, on: :collection
  end
  resources :holders do
    get :find, on: :collection
  end
  resources :producers  do
    get :find, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :drugs do
    get :search, on: :collection
    get :wide_search, on: :collection
    get :body_clicked_search, on: :collection
    get :show, on: :collection
  end

  root :to => 'home#index'

  match '/drugs/:id'           =>  'drugs#show',                      via: :get
  match 'holders/:name/find'   =>  'holders#find',                    :as => 'holders_find'
  match 'holders/:id/drugs'    =>  'holders#show_all',                :as => 'holders_show_all_drugs'
  match 'suppliers/:name/find' =>  'suppliers#find',                  :as => 'suppliers_find'
  match 'suppliers/:id/drugs'  =>  'suppliers#show_all',              :as => 'suppliers_show_all_drugs'
  match 'producers/:name/find' =>  'producers#find',                  :as => 'producers_find'
  match 'producers/:id/drugs'  =>  'producers#show_all',              :as => 'producers_show_all_drugs'
  match '/signin',             to: 'sessions#new'
  match '/signout',            to: 'sessions#destroy',                via: :delete
  match '/about',              to: 'static_pages#about'
  match '/contact',            to: 'static_pages#contact'
  match '/find_specific',      to: 'home#findSpecific'
  match '/stats',              to: 'statistics#stats'
  match '/find_producers',     to: 'producers#find_producers'
  match '/find_suppliers',     to: 'suppliers#find_suppliers'
  match '/find_holders',       to: 'holders#find_holders'
  match '/human_body',         to: 'static_pages#body'
  match '/clicks/:id',         to: 'clicks#incr_clicks',              via: :post

end

app/models/supplier.rb
# == Schema Information
#
# Table name: suppliers
#
#  id         :integer          not null, primary key
#  name       :string(400)
#  name_clean :string(400)
#

class Supplier < ActiveRecord::Base
  attr_accessible :id, :name
  has_many :drugs

  def self.find_supplier_like_name name
    Supplier.where(["name_clean ILIKE ?", "#{name}%"])
  end

  def self.find_by_supplier_id id
    Drug.where("supplier_id = ?", "#{id}")
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def find
    @producer = Supplier.find_supplier_like_name params[:name]
  end

  def show_all
    drug_ = Supplier.find_by_supplier_id params[:id]
    @drug = drug_.paginate(page: params[:page])
  end

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suppliers }
    end
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/new
  # GET /suppliers/new.json
  def new
    @supplier = Supplier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/1/edit
  def edit
    @supplier = Supplier.find(params[:id])
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(params[:supplier])

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render json: @supplier, status: :created, location: @supplier }
      else
        format.html { render action: "new" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suppliers/1
  # PUT /suppliers/1.json
  def update
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      if @supplier.update_attributes(params[:supplier])
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_for(@supplier) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id, :placeholder => Supplier.last.id + 1 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/find.erb
<p id="notice"><%= notice %></p>

<%= render 'producers/organization' %>

app/views/suppliers/find_suppliers.html.erb
<% provide(:title, 'Rozšírené vyhľadávanie') %>

<div class="center hero-unit">
  <h1>Nájdi dodávateľa</h1>

  <%= form_tag find_suppliers_path, method: :get do %>

      <p>
        <%= text_field_tag(:name, '', :placeholder => 'Zadajte názov organizácie     Príklad: BOIRON') %>
        <%= submit_tag 'Hľadaj', class: "btn btn-large btn-primary" %>
      </p>

  <% end %>
</div>

app/views/suppliers/index.html.erb
<h1>Listing suppliers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suppliers.each do |supplier| %>
  <tr>
    <td><%= supplier.id %></td>
    <td><%= supplier.name %></td>
    <td><%= link_to 'Show', supplier %></td>
    <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
    <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Nový dodávateľ</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @supplier.id %>
</p>

<p>
  <b>Name:</b>
  <%= @supplier.name %>
</p>


<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show_all.erb
<p id="notice"><%= notice %></p>

<%= render :template => 'drugs/_drug' %>