config/routes.rb
DrugFinderDb::Application.routes.draw do
  resources :statistics
  resources :users
  resources :suppliers  do
     get :find, on: :collection
  end
  resources :holders do
    get :find, on: :collection
  end
  resources :producers  do
    get :find, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :drugs do
    get :search, on: :collection
    get :wide_search, on: :collection
    get :body_clicked_search, on: :collection
    get :show, on: :collection
  end

  root :to => 'home#index'

  match '/drugs/:id'           =>  'drugs#show',                      via: :get
  match 'holders/:name/find'   =>  'holders#find',                    :as => 'holders_find'
  match 'holders/:id/drugs'    =>  'holders#show_all',                :as => 'holders_show_all_drugs'
  match 'suppliers/:name/find' =>  'suppliers#find',                  :as => 'suppliers_find'
  match 'suppliers/:id/drugs'  =>  'suppliers#show_all',              :as => 'suppliers_show_all_drugs'
  match 'producers/:name/find' =>  'producers#find',                  :as => 'producers_find'
  match 'producers/:id/drugs'  =>  'producers#show_all',              :as => 'producers_show_all_drugs'
  match '/signin',             to: 'sessions#new'
  match '/signout',            to: 'sessions#destroy',                via: :delete
  match '/about',              to: 'static_pages#about'
  match '/contact',            to: 'static_pages#contact'
  match '/find_specific',      to: 'home#findSpecific'
  match '/stats',              to: 'statistics#stats'
  match '/find_producers',     to: 'producers#find_producers'
  match '/find_suppliers',     to: 'suppliers#find_suppliers'
  match '/find_holders',       to: 'holders#find_holders'
  match '/human_body',         to: 'static_pages#body'
  match '/clicks/:id',         to: 'clicks#incr_clicks',              via: :post

end

app/models/holder.rb
# == Schema Information
#
# Table name: holders
#
#  id         :integer          not null, primary key
#  name       :string(400)
#  name_clean :string(400)
#

class Holder < ActiveRecord::Base
  attr_accessible :id, :name
  has_many :drugs

  def self.find_holders_like_name name
    Holder.where(["name_clean ILIKE ?", "#{name}%"])
  end

  def self.find_by_holder_id id
    Drug.where("holder_id = ?", "#{id}")
  end

end

app/controllers/holders_controller.rb
class HoldersController < ApplicationController

  def find
    @producer = Holder.find_holders_like_name params[:name]
  end

  def show_all
    drug_ = Holder.find_by_holder_id params[:id]
    @drug = drug_.paginate(page: params[:page])
  end

  # GET /holders
  # GET /holders.json
  def index
    @holders = Holder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @holders }
    end
  end

  # GET /holders/1
  # GET /holders/1.json
  def show
    @holder = Holder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @holder }
    end
  end

  # GET /holders/new
  # GET /holders/new.json
  def new
    @holder = Holder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @holder }
    end
  end

  # GET /holders/1/edit
  def edit
    @holder = Holder.find(params[:id])
  end

  # POST /holders
  # POST /holders.json
  def create
    @holder = Holder.new(params[:holder])

    respond_to do |format|
      if @holder.save
        format.html { redirect_to @holder, notice: 'Holder was successfully created.' }
        format.json { render json: @holder, status: :created, location: @holder }
      else
        format.html { render action: "new" }
        format.json { render json: @holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /holders/1
  # PUT /holders/1.json
  def update
    @holder = Holder.find(params[:id])

    respond_to do |format|
      if @holder.update_attributes(params[:holder])
        format.html { redirect_to @holder, notice: 'Holder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holders/1
  # DELETE /holders/1.json
  def destroy
    @holder = Holder.find(params[:id])
    @holder.destroy

    respond_to do |format|
      format.html { redirect_to holders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/holders_helper.rb
module HoldersHelper
end

app/views/holders/_form.html.erb
<%= form_for(@holder) do |f| %>
  <% if @holder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holder.errors.count, "error") %> prohibited this holder from being saved:</h2>

      <ul>
      <% @holder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id, :placeholder => Holder.last.id + 1 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holders/edit.html.erb
<h1>Editing holder</h1>

<%= render 'form' %>

<%= link_to 'Show', @holder %> |
<%= link_to 'Back', holders_path %>

app/views/holders/find.erb
<p id="notice"><%= notice %></p>

<%= render 'producers/organization' %>

app/views/holders/find_holders.html.erb
<% provide(:title, 'Rozšírené vyhľadávanie') %>

<div class="center hero-unit">
  <h1>Nájdi držiteľa</h1>

  <%= form_tag find_holders_path, method: :get do %>

      <p>
        <%= text_field_tag(:name, '', :placeholder => 'Zadajte názov organizácie     Príklad: BOIRON') %>
        <%= submit_tag 'Hľadaj', class: "btn btn-large btn-primary" %>
      </p>

  <% end %>
</div>

app/views/holders/index.html.erb
<h1>Listing holders</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @holders.each do |holder| %>
  <tr>
    <td><%= holder.id %></td>
    <td><%= holder.name %></td>
    <td><%= link_to 'Show', holder %></td>
    <td><%= link_to 'Edit', edit_holder_path(holder) %></td>
    <td><%= link_to 'Destroy', holder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Holder', new_holder_path %>

app/views/holders/new.html.erb
<h1>Nový držiteľ</h1>

<%= render 'form' %>

<%= link_to 'Back', holders_path %>

app/views/holders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @holder.id %>
</p>

<p>
  <b>Name:</b>
  <%= @holder.name %>
</p>


<%= link_to 'Edit', edit_holder_path(@holder) %> |  <%= link_to 'Destroy', @holder, method: :delete, data: { confirm: 'Are you sure?' } %> <br>
<%= link_to 'Back', holders_path %>

app/views/holders/show_all.erb
<p id="notice"><%= notice %></p>

<%= render :template => 'drugs/_drug' %>