config/routes.rb
DrugFinderDb::Application.routes.draw do
  resources :statistics
  resources :users
  resources :suppliers  do
     get :find, on: :collection
  end
  resources :holders do
    get :find, on: :collection
  end
  resources :producers  do
    get :find, on: :collection
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :drugs do
    get :search, on: :collection
    get :wide_search, on: :collection
    get :body_clicked_search, on: :collection
    get :show, on: :collection
  end

  root :to => 'home#index'

  match '/drugs/:id'           =>  'drugs#show',                      via: :get
  match 'holders/:name/find'   =>  'holders#find',                    :as => 'holders_find'
  match 'holders/:id/drugs'    =>  'holders#show_all',                :as => 'holders_show_all_drugs'
  match 'suppliers/:name/find' =>  'suppliers#find',                  :as => 'suppliers_find'
  match 'suppliers/:id/drugs'  =>  'suppliers#show_all',              :as => 'suppliers_show_all_drugs'
  match 'producers/:name/find' =>  'producers#find',                  :as => 'producers_find'
  match 'producers/:id/drugs'  =>  'producers#show_all',              :as => 'producers_show_all_drugs'
  match '/signin',             to: 'sessions#new'
  match '/signout',            to: 'sessions#destroy',                via: :delete
  match '/about',              to: 'static_pages#about'
  match '/contact',            to: 'static_pages#contact'
  match '/find_specific',      to: 'home#findSpecific'
  match '/stats',              to: 'statistics#stats'
  match '/find_producers',     to: 'producers#find_producers'
  match '/find_suppliers',     to: 'suppliers#find_suppliers'
  match '/find_holders',       to: 'holders#find_holders'
  match '/human_body',         to: 'static_pages#body'
  match '/clicks/:id',         to: 'clicks#incr_clicks',              via: :post

end

app/views/layouts/_footer.erb
<footer class="footer">
  <nav>
    <ul>
     <li><%= link_to 'O nás', '/about' %></li>                        &nbsp;
     <li><%= link_to 'Kontakt', '/contact' %></li>                    &nbsp;
     <li><%= link_to 'Fakulta', 'http://www.fiit.stuba.sk' %></li>    &nbsp;
     <li><%= link_to 'Štatistiky', '/stats' %></li>                   &nbsp;
    </ul>
  </nav>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%#--= link_to "DrugFinder", root_url, id: "logo" %>
      <!--img src="Medical_Symbol.png", id:-->
      <nav>
        <ul class="nav pull-right">

         <li><%= link_to 'Domov', root_path %></li>
         <li><%= link_to 'Čo Vás bolí ?', '/human_body' %>
         <!--li><%= link_to 'Hľadať podľa mena', '/find_specific' %></li-->

          <li id="menu" class="dropdown">
            <a href="dropdown-menu" class="dropdown-toggle" data-toggle="dropdown">
              Hľadaj organizácie<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <div class="pomocna">
                 <li><%= link_to 'Hľadaj výrobcu', '/find_producers' %></li>
                 <li><%= link_to 'Hľadaj držiteľa', '/find_holders' %></li>
                 <li><%= link_to 'Hľadaj dodávateľa', '/find_suppliers' %></li>
              </div>
            </ul>
          </li>
             <% if signed_in? && current_user.admin? %>
              <li id="menu" class="dropdown">
                <a href="dropdown-menu 2" class="dropdown-toggle" data-toggle="dropdown">
                  Účet<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Pridaj nový liek', new_drug_path %></li>
                  <li><%= link_to 'Pridaj nového výrobcu', new_producer_path %></li>
                  <li><%= link_to 'Pridaj nového držiteľa', new_holder_path %></li>
                  <li><%= link_to 'Pridaj nového dodávateľa', new_supplier_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Odhlásiť', signout_path, method: 'delete' %></li>
                </ul>
              </li>
          <% else %>
            <!--li><%#--= link_to 'Prihlásiť',  '/signin' %></li-->
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', 'token-input',  media: 'all' %>
  <%= javascript_include_tag 'application', 'jquery.tokeninput' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if flash[:notice] %>
      <div id="notice"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>